-- Repeatable migration:
-- Keep this file aligned with backend data contracts.
-- Flyway reruns this script whenever content changes.

CREATE TABLE IF NOT EXISTS yonghu (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  yonghuming VARCHAR(64) NOT NULL,
  mima VARCHAR(128) NOT NULL,
  xingming VARCHAR(64),
  touxiang VARCHAR(255),
  xingbie VARCHAR(16),
  lianxidianhua VARCHAR(32),
  money DECIMAL(12, 2) NOT NULL DEFAULT 0,
  shimingrenzheng VARCHAR(32) NOT NULL DEFAULT '未认证',
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS yonghuming VARCHAR(64) NOT NULL;
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS mima VARCHAR(128) NOT NULL;
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS xingming VARCHAR(64);
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS touxiang VARCHAR(255);
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS xingbie VARCHAR(16);
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS lianxidianhua VARCHAR(32);
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS money DECIMAL(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS shimingrenzheng VARCHAR(32) NOT NULL DEFAULT '未认证';
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE yonghu ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE yonghu ADD UNIQUE INDEX IF NOT EXISTS uk_yonghu_username (yonghuming);
ALTER TABLE yonghu ADD UNIQUE INDEX IF NOT EXISTS uk_yonghu_phone (lianxidianhua);

CREATE TABLE IF NOT EXISTS address (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  userid BIGINT NOT NULL,
  address VARCHAR(255) NOT NULL,
  name VARCHAR(64) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  isdefault VARCHAR(8) NOT NULL DEFAULT '否',
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE address ADD COLUMN IF NOT EXISTS userid BIGINT NOT NULL;
ALTER TABLE address ADD COLUMN IF NOT EXISTS address VARCHAR(255) NOT NULL;
ALTER TABLE address ADD COLUMN IF NOT EXISTS name VARCHAR(64) NOT NULL;
ALTER TABLE address ADD COLUMN IF NOT EXISTS phone VARCHAR(32) NOT NULL;
ALTER TABLE address ADD COLUMN IF NOT EXISTS isdefault VARCHAR(8) NOT NULL DEFAULT '否';
ALTER TABLE address ADD COLUMN IF NOT EXISTS addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE address ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE address ADD INDEX IF NOT EXISTS idx_address_userid (userid);
