CREATE TABLE IF NOT EXISTS yonghu (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  yonghuming VARCHAR(64) NOT NULL,
  mima VARCHAR(128) NOT NULL,
  xingming VARCHAR(64),
  touxiang VARCHAR(255),
  xingbie VARCHAR(16),
  lianxidianhua VARCHAR(32),
  money DECIMAL(12, 2) NOT NULL DEFAULT 0,
  shimingrenzheng VARCHAR(32) NOT NULL DEFAULT '未认证',
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_yonghu_username (yonghuming),
  UNIQUE KEY uk_yonghu_phone (lianxidianhua)
);

CREATE TABLE IF NOT EXISTS address (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  userid BIGINT NOT NULL,
  address VARCHAR(255) NOT NULL,
  name VARCHAR(64) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  isdefault VARCHAR(8) NOT NULL DEFAULT '否',
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_address_userid (userid)
);
