ALTER TABLE users COMMENT='用户表';
ALTER TABLE users
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  MODIFY COLUMN yonghuming VARCHAR(64) NOT NULL COMMENT '登录账号（用户名或手机号）',
  MODIFY COLUMN mima VARCHAR(128) NOT NULL COMMENT '密码哈希',
  MODIFY COLUMN xingming VARCHAR(64) NULL COMMENT '姓名',
  MODIFY COLUMN touxiang VARCHAR(255) NULL COMMENT '头像URL',
  MODIFY COLUMN xingbie VARCHAR(16) NULL COMMENT '性别',
  MODIFY COLUMN lianxidianhua VARCHAR(32) NULL COMMENT '联系电话',
  MODIFY COLUMN money DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '账户余额',
  MODIFY COLUMN shimingrenzheng VARCHAR(32) NOT NULL DEFAULT '未认证' COMMENT '实名认证状态',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_addresses COMMENT='用户地址表';
ALTER TABLE user_addresses
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '地址ID',
  MODIFY COLUMN userid BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN address VARCHAR(255) NOT NULL COMMENT '详细地址',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '收货人姓名',
  MODIFY COLUMN phone VARCHAR(32) NOT NULL COMMENT '联系电话',
  MODIFY COLUMN isdefault VARCHAR(8) NOT NULL DEFAULT '否' COMMENT '是否默认地址',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE route_categories COMMENT='线路分类表';
ALTER TABLE route_categories
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  MODIFY COLUMN xianlufenlei VARCHAR(64) NOT NULL COMMENT '分类名称',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE travel_routes COMMENT='旅游线路表';
ALTER TABLE travel_routes
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '线路ID',
  MODIFY COLUMN xianlumingcheng VARCHAR(255) NOT NULL COMMENT '线路名称',
  MODIFY COLUMN xianlufenlei VARCHAR(64) NULL COMMENT '线路分类',
  MODIFY COLUMN fengmiantu VARCHAR(255) NULL COMMENT '封面图URL',
  MODIFY COLUMN jingdianmingcheng VARCHAR(255) NULL COMMENT '景点名称',
  MODIFY COLUMN chufadi VARCHAR(64) NULL COMMENT '出发地',
  MODIFY COLUMN mudedi VARCHAR(64) NULL COMMENT '目的地',
  MODIFY COLUMN jiaotongfangshi VARCHAR(32) NULL COMMENT '交通方式',
  MODIFY COLUMN chuxingshijian VARCHAR(64) NULL COMMENT '出行时间',
  MODIFY COLUMN feiyongbaohan TEXT NULL COMMENT '费用包含',
  MODIFY COLUMN xingchengluxian LONGTEXT NULL COMMENT '行程路线',
  MODIFY COLUMN clicktime VARCHAR(64) NULL COMMENT '最近点击时间',
  MODIFY COLUMN clicknum INT NOT NULL DEFAULT 0 COMMENT '点击量',
  MODIFY COLUMN price DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '价格',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE latest_routes COMMENT='最新线路表';
ALTER TABLE latest_routes
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '线路ID',
  MODIFY COLUMN xianlumingcheng VARCHAR(255) NOT NULL COMMENT '线路名称',
  MODIFY COLUMN xianlufenlei VARCHAR(64) NULL COMMENT '线路分类',
  MODIFY COLUMN fengmiantu VARCHAR(255) NULL COMMENT '封面图URL',
  MODIFY COLUMN jingdianmingcheng VARCHAR(255) NULL COMMENT '景点名称',
  MODIFY COLUMN chufadi VARCHAR(64) NULL COMMENT '出发地',
  MODIFY COLUMN mudedi VARCHAR(64) NULL COMMENT '目的地',
  MODIFY COLUMN jiaotongfangshi VARCHAR(32) NULL COMMENT '交通方式',
  MODIFY COLUMN chuxingshijian VARCHAR(64) NULL COMMENT '出行时间',
  MODIFY COLUMN feiyongbaohan TEXT NULL COMMENT '费用包含',
  MODIFY COLUMN xingchengluxian LONGTEXT NULL COMMENT '行程路线',
  MODIFY COLUMN clicktime VARCHAR(64) NULL COMMENT '最近点击时间',
  MODIFY COLUMN clicknum INT NOT NULL DEFAULT 0 COMMENT '点击量',
  MODIFY COLUMN price DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '价格',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE travel_news COMMENT='旅游资讯表';
ALTER TABLE travel_news
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '资讯ID',
  MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '资讯标题',
  MODIFY COLUMN introduction TEXT NULL COMMENT '资讯简介',
  MODIFY COLUMN picture VARCHAR(255) NULL COMMENT '封面图URL',
  MODIFY COLUMN content LONGTEXT NULL COMMENT '资讯内容',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE shopping_cart COMMENT='购物车表';
ALTER TABLE shopping_cart
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '购物车项ID',
  MODIFY COLUMN userid BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN tablename VARCHAR(64) NOT NULL COMMENT '来源业务表名',
  MODIFY COLUMN goodid BIGINT NOT NULL COMMENT '商品/线路ID',
  MODIFY COLUMN goodname VARCHAR(255) NULL COMMENT '商品名称',
  MODIFY COLUMN picture VARCHAR(255) NULL COMMENT '商品图片URL',
  MODIFY COLUMN buynumber INT NOT NULL DEFAULT 1 COMMENT '购买数量',
  MODIFY COLUMN price DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '单价',
  MODIFY COLUMN discountprice DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '折扣价',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE purchase_orders COMMENT='订单表';
ALTER TABLE purchase_orders
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单记录ID',
  MODIFY COLUMN userid BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN orderid VARCHAR(64) NOT NULL COMMENT '订单号',
  MODIFY COLUMN tablename VARCHAR(64) NULL COMMENT '来源业务表名',
  MODIFY COLUMN goodid BIGINT NULL COMMENT '商品/线路ID',
  MODIFY COLUMN goodname VARCHAR(255) NULL COMMENT '商品名称',
  MODIFY COLUMN picture VARCHAR(255) NULL COMMENT '商品图片URL',
  MODIFY COLUMN buynumber INT NOT NULL DEFAULT 1 COMMENT '购买数量',
  MODIFY COLUMN price DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '单价',
  MODIFY COLUMN discountprice DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '折扣价',
  MODIFY COLUMN total DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '订单总价',
  MODIFY COLUMN discounttotal DECIMAL(12, 2) NOT NULL DEFAULT 0 COMMENT '折后总价',
  MODIFY COLUMN type INT NOT NULL DEFAULT 1 COMMENT '订单类型',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT '未支付' COMMENT '订单状态',
  MODIFY COLUMN address VARCHAR(255) NULL COMMENT '收货地址',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE favorites COMMENT='收藏表';
ALTER TABLE favorites
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '收藏ID',
  MODIFY COLUMN userid BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN refid BIGINT NOT NULL COMMENT '被收藏对象ID',
  MODIFY COLUMN tablename VARCHAR(64) NOT NULL COMMENT '被收藏对象表名',
  MODIFY COLUMN name VARCHAR(255) NULL COMMENT '收藏标题',
  MODIFY COLUMN picture VARCHAR(255) NULL COMMENT '收藏图片URL',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE support_chats COMMENT='客服聊天记录表';
ALTER TABLE support_chats
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '消息ID',
  MODIFY COLUMN userid BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN adminid BIGINT NULL COMMENT '客服ID',
  MODIFY COLUMN ask TEXT NULL COMMENT '用户提问',
  MODIFY COLUMN reply TEXT NULL COMMENT '客服回复',
  MODIFY COLUMN isreply INT NOT NULL DEFAULT 0 COMMENT '是否为回复消息',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE user_gallery COMMENT='用户相册表';
ALTER TABLE user_gallery
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '相册记录ID',
  MODIFY COLUMN userid BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN title VARCHAR(255) NULL COMMENT '照片标题',
  MODIFY COLUMN photoUrl VARCHAR(255) NULL COMMENT '照片URL',
  MODIFY COLUMN note TEXT NULL COMMENT '备注',
  MODIFY COLUMN takenAt VARCHAR(64) NULL COMMENT '拍摄时间',
  MODIFY COLUMN location VARCHAR(255) NULL COMMENT '拍摄地点',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE trip_plans COMMENT='行程规划表';
ALTER TABLE trip_plans
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '行程ID',
  MODIFY COLUMN userid BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN title VARCHAR(255) NULL COMMENT '行程标题',
  MODIFY COLUMN payload LONGTEXT NULL COMMENT '行程详情JSON',
  MODIFY COLUMN addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
